<?php

/**
 * Implementation of hook_views_api().
 */
function views_showup_views_api() {
  return array('api' => 2);
}

/**
 * Template function for views_showup
 *
 * @param array $vars
 *  Array of template variables.
 */
function template_preprocess_views_view_showup(&$vars) {
  $mpath = drupal_get_path('module', 'views_showup');

  $view = $vars['view'];

  $vars['views_showup_id'] = 'views-showup-'. $view->name .'-'. $view->current_display;

  $options = $vars['options'];
  if ($options['views_showup_effect_speed'] == 'custom') {
    $options['views_showup_effect_speed'] = $options['views_showup_effect_speed_custom'];
  }
  unset($options['grouping']);

  $settings['views_showup'] = array(
    $vars['views_showup_id'] => $options,
  );

  drupal_add_js($settings, 'setting');
  drupal_add_js($mpath .'/js/views_showup.js');
  drupal_add_css($mpath. '/css/views_showup.css');
}

/**
 * Implementation of hook_theme().
 */
function views_showup_theme() {
  return array(
    /*'views_view_field__v0707000801__page_1__title' => array(
      'arguments' => array('view' => NULL, 'field' => NULL, 'row' => NULL),
      'template' => 'views-view-field--v0707000801--page-1--title',
      'original hook' => 'views_view_field',
      'path' => drupal_get_path('module', 'views_showup') .'/theme',
    ),*/
    // Copy theme/views-view-field--v0707000801--title.tpl.php to theme directory.
    /*'views_view_field__v0707000801__title' => array(
      'arguments' => array('view' => NULL, 'field' => NULL, 'row' => NULL),
      'template' => 'views-view-field--v0707000801--title',
      'original hook' => 'views_view_field',
      'path' => drupal_get_path('module', 'views_showup') .'/theme',
    ),*/
  );
}
